### ISSUE TITLE
spelling mistakes

### ISSUE THREAD

**Issue by ArjenR49** [hellresistor/Rpi-UPSplus-HA#2]
If I want to go over your code and correct spelling mistakes, how do I go about it?

Do I download the shell script, correct the spelling mistakes and then upload the result somewhere, so you can see what I changed and possibly approve the changes? Where do I upload the result?
I have seen files with changes marked, but the only way I have applied my own changes which were made in an earlier version to a newer version of e.g. fanShutDownUPS.py is using the Kompare program (linux), never on Github.
It's not the Github way, but it was easier for me.

Another thing:
In the actual code you use the correct name mqtt, but everywhere else you have spelled it MQQT.

**Comment by hellresistor** [comment]
You need to fork the repository, which will enable the code in your github account, which will allow you to edit the code.

Here you have 2 options:
 - You edit the files on the web (I use this method, for small things/file by file).
 - You download the Github Desktop. (I think it's more boring)

After you make the Changes (all saved). You have a Menu that says "Pull Request".
Here you will indicate The destination and Source. from YOUR FORKED repository TO the source repository
