### ISSUE TITLE
broker name?

### ISSUE THREAD

**Issue by ArjenR49** [hellresistor/Rpi-UPSplus-HA#3]
I did all the parts of your installation script except the GeeekPi UPS script installation. I just enabled the RTC following Geeekpi's instructions manually, because that I had not done yet on this new test installation. I don't run the Geekpi scripts, I use fanShutDownUPS.py.

It's is essentially better made. It has exception handling, which is needed on i2c operations. When I run MotionEye on that Pi, I get i2c errors and frtz13's scripts handles them, so the script doesn't crash. Without MotionEye, no i2c timeouterrors to be seen in the journal ... GeekPi's script doesn't handle the timeout errors at all.

I did wonder during installation of dependencies that it installed smbus2, even though I was already using smbus2 because fanShutDownUPS.py needs it, of course. Also python and so on were installed, I think, but I already had those, too. Strange.
Some of the dependencies were skipped, as I already had them.

I opened the URL given at the end of the shell script execution from my laptop and logged in to HA (probably made the account then, but I already had account name and password chosen for the earlier attempts using IOTstack). 

I get an HA web page and even though I got to see stuff like the weather here, I am essentially at a loss. What next?

I can switch off our TV and there's something concerning our Chromecast, too.
Everything is an 'entity' and that's when I get lost in newspeak.
Supposedly you can play stuff on the TV from a library(?) ... We don't have HBO or Netflix of what have you pay tv. There's enough on TV without those ;-)

I tried to 'activate' MQTT, but it wants the name of the broker. I have no idea ... I never gave a broker a name. Broker would have been fine by me.

Now I do see a long list of sensors, of which none work. They only open empty graphs. Battery power, temperature etc. etc. all Not available (in dutch ....).

Also notifications about several things which I tried to solve. Some Network UPS Tools (NUT), which wants some info I don't know, because I never even had heard of it.

And then there are some binary sensors also. One works and it is about the RPI Power. I have seen that one when I tried IOTstack. What does it tell me? If I would switch the PI off, it would perhaps tell me .... No, it wouldn't tell me anything, because all that HA and MQTT stuff is running on the very Pi ...

So ... everything installed after a fashion, but now there's too many unknown entieties again, like in the IOTstack trial. Even I am an unknown entity to it.

In the Pi's GUI menu there is absolutely nothing about MQTT or HA. And I haven't found the installation folders on the Pi. Somewhere outside /home/pi?

Fortunately the networking still seems to be working although I saw the installation disabled something to do with networking. I access my Pi(s) through VNC, by the way.

I 100% believe it works for some people, but it is like moving in a fog.

**Comment by hellresistor** [comment]
When you run this script last time?  i have done some changes since yesterday..
@ArjenR49

**Comment by ArjenR49** [comment]
I took the ZIP file from the github site yesterday and noticed a little later that you had changed the shell script like one hour ago. I had already started installing in steps. I then checked the changes and it looked I had the changed script.

Maybe I'll download the shell script again and delete the parts that I have done manually, in a different way or should be ok already.

I'd rather have written instructions with command lines than a script that automatically does a whole load of things of which I want to know beforehand what it does and where.

Before running install commands again, I will want to remove the stuff which is left from the previous installation attempt, so it cannot possibly be the source of problems again. SO since I don't know what is put where, I'll have to restore the clone from before I started this HA stuff.

There is something wrong with the MQTT and HA stuff . They're not working together as far as the UPS is concerned. The Pi's IP as broker name is not accepted my MQTT but another name like broker is even worse. Broker NAME is perhaps a misnomer and it actually means ip address of the MTTQ broker machine.

**Comment by hellresistor** [comment]
> I took the ZIP file from the github site yesterday and noticed a little later that you had changed the shell script like one hour ago. I had already started installing in steps. I then checked the changes and it looked I had the changed script.


Definely just today are working ( i have wake up 4AM to start work on this) Because it was very problematic. That version will Replace the original configuration.yaml file AND NOT APPEND!

will close because related with a outdated script.

BUT if you need help. I try help you.
