### ISSUE TITLE
use of /root was a bad idea, for me at least

### ISSUE THREAD

**Issue by ArjenR49** [hellresistor/Rpi-UPSplus-HA#4]

**Comment by hellresistor** [comment]
needed to install HA supervised and sure use `sudo -i` command to enter on root user. It is a known issue from HA community

**Comment by ArjenR49** [comment]
When I noticed that fanShutDownups.py was running twice, I set out to find why and how.

I had misssed the code in your script that puts frtz13 scripts etc on /root ....
So, I set out to remove it and have all run as pi  from /home/pi ...
I figured I better copy some files to be able to change my own accordingly, before removing the scripts and the other added folder from /root.
In /root you can only use the terminal and ---- you can guess how this ended ..... I wiped out all of /root.
The Pi is still running, but I may have to restore from a clone of the SSD ...

I am by no means an authority on Linux, but for me installing files in /root and running stuff as root when it isn't necessary is not a good idea, IMO. I have been running ftrz13's files as pi and they reside under /home/pi. I haven't noticed that frtz13 had intended it any other way.

I will try to copy just the /root folder from my clone... maybe I can still save the day ...

**Comment by hellresistor** [comment]
friend run command  `sudo crontab -e` (on both users, pi and root)
and remove the lines you need.

My script put the @ftrz13 on root and edit/configure the files.

This is suppose to run on CLI environment, using ssh/putty

Please run commands as pi user and with sudo ... `sudo cp origin target`

**Comment by ArjenR49** [comment]
I can do all that, but I didn't know it was going to install frtz13's stuff - I already have it running - and when I was removing the stuff from /root, I made a mistake, which one wouldn't easily make in the GUI.
Anyway, I copied /root from the clone and started my Pi. OK.
Had a look at the ini file and made the same changes in tghe ini file that I already had in place, and then put the yaml file where the frtz13 scripts are (not /home/pi/scripts, which is too generic in my opinion).
Reboot.
No luck.
The Pi's ip address is not accepted by MQTT for the broker name.
I could change it in the ini file to something else and then try in HA again, but haven't tried yet ...

**Comment by hellresistor** [comment]
> I can do all that, but I didn't know it was going to install frtz13's stuff - I already have it running - and when I was removing the stuff from /root, I made a mistake, which one wouldn't easily make in the GUI.

Well the script check run has root user :| 

> Had a look at the ini file and made the same changes in tghe ini file that I already had in place, and then put the yaml file where the frtz13 scripts are (not /home/pi/scripts, which is too generic in my opinion).

The yaml file is to COPY PASTE the content and append into` configuration.yaml` file . is NOT to copy the file!
Your problem should be knows HA `configuration.yaml` file path.: ` /usr/share/hassio/homeassistant/configuration.yaml`

> The Pi's ip address is not accepted by MQTT for the broker name.
> I could change it in the ini file to something else and then try in HA again, but haven't tried yet ...

Have you the `mosquitto` package installed on raspbian?

Last question: When you execute my Bash, yesterday?

PS: Sorry my bad english ou misterpretation , English was not my native language

**Comment by hellresistor** [comment]
https://github.com/hellresistor/Rpi-UPSplus-HA/issues/3#issuecomment-851040527

And I will see about executing python scripts on as a pi user and not root! will work on that!

**Comment by ArjenR49** [comment]
mosquitto in installed in the beginning of the script, isn't it? I installed all the dependencies and was just surprised some stuff was installed which was already installed like smbus2.

**Comment by hellresistor** [comment]
> mosquitto in installed in the beginning of the script, isn't it? I installed all the dependencies and was just surprised some stuff was installed which was already installed like smbus2.

and more front a configuration step

Run this

```
sudo cat >>  /etc/mosquitto/conf.d/mosquitto.conf <<EOTF
allow_anonymous false
password_file /etc/mosquitto/conf.d/pwfile
port 1883
EOTF
sudo service restart mosquitto
```
need add a mosquitto user
`sudo mosquitto_passwd -c /etc/mosquitto/conf.d/pwfile $MYMQQTUSER`  Replace $MYMQQTUSER to your mosquitto user

on .ini file should be:
`BROKER=$IPMACHINE` Replace $IPMACHINE to local ip 192.168.1.X (rpi IP)

Add this into /usr/share/hassio/homeassistant/configuration.yaml file
```
# Local MQQT server
mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: $IPMACHINE
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: $MYMQQTUSER
  password: $MYMQQTPASS
```

Add the sensors too (att: that are ALL SENSORES avaliable, just delete what you not need)

**Comment by hellresistor** [comment]
> [#3 (comment)](https://github.com/hellresistor/Rpi-UPSplus-HA/issues/3#issuecomment-851040527)
> 
> And I will see about executing python scripts on as a pi user and not root! will work on that!

@ArjenR49  To be clarify
DONE :
- Script UPSplus not implement
- Script @frtz13 on /home/pi user

Tomorrow. I will test. Done today.. enaught. :)
