### ISSUE TITLE
Mosquitto password

### ISSUE THREAD

**Issue by ArjenR49** [hellresistor/Rpi-UPSplus-HA#5]
I have done the whole thing again after downloading the latest version an hour or so ago.
...
There is a problem copying a password from my laptop to a terminal window on the Pi in a VNC session, so it's impossible to tell what is copied when the script asks for the password.

I had noticed the use of sudo mosquitto_passwd in the script and assumed it is used to encrypt the password.
Help for that program revealed different ways of using it.
In the script it is used with the -c flag. I couldn't find out where it gets the clear text password from to encrypt in that case.
So I tried the following in a terminal:
sudo mosquitto_passwd -b /etc/mosquitto/conf.d/pwfile <username> <password>

This time I had success starting MQTT service.

I had ran the latter part of the install script many times without success before this. It may have been because of the problem with copying passwords from the laptop (KeepassXC ...) to the VNC session, or there is a mistake in the password encryption in the script.

**Comment by hellresistor** [comment]
yes!! sure!

execute `sudo  mosquitto_passwd -h` and see options ;)

it because the variable `$MQQTPASSWORD` will have a password
and `mosquitto_passwd` command will ask a password for `$MQQTUSER`. and people will commit error enter other password :) . I will correct that tomorrow. will be auto without ask password
ThNK YOU

**Comment by hellresistor** [comment]
Done but not tested yet.

**Comment by ArjenR49** [comment]
I saw your correction. You had to jump through hoops to enter the password twice in the script, but you could also use this form:
sudo mosquitto_passwd -b /etc/mosquitto/conf.d/pwfile $MYMQQTUSER $MYMQQTPASS
This is what I used to correct the encrypted password.

In the above the username and password which I had originally written between < and >, had disappeared.

BTW: the spelling of MQQT is wrong. It can be easily changed throughout the script from MQQT to MQTT.

**Comment by hellresistor** [comment]
```
 mosquitto_passwd -h
mosquitto_passwd is a tool for managing password files for mosquitto.

Usage: mosquitto_passwd [-c | -D] passwordfile username
       mosquitto_passwd -b passwordfile username password
       mosquitto_passwd -U passwordfile
 -b : run in batch mode to allow passing passwords on the command line.
 -c : create a new password file. This will overwrite existing files.
 -D : delete the username rather than adding/updating its password.
 -U : update a plain text password file to use hashed passwords.
```
with -c will create the file with password encrypted/hashed. It is good info to troubleshooting. 
I am just following HA Community tips.
