### ISSUE TITLE
For consideration

### ISSUE THREAD

**Issue by ArjenR49** [hellresistor/Rpi-UPSplus-HA#6]
As I understand it now, HA and Mosquitto could be run on a different machine (Pi) as the one that the UPS is powering.
The installation script could take that into account by separating the UPS stuff from the HA & MQTT stuff into two scripts. One for the HA & MQTT server and another for the Pi with the UPS.

If you have several UPS's you wouldn't want all those PI's to have their own installations of HA & Mosquitto, I think. They would only need the MQTT client, as I understand it.

**Comment by hellresistor** [comment]
> As I understand it now, HA and Mosquitto could be run on a different machine (Pi) as the one that the UPS is powering.
Yes, you can have dedicated servers if you wish.
 
> If you have several UPS's you wouldn't want all those PI's to have their own installations of HA & Mosquitto, I think. They would only need the MQTT client, as I understand it.

I understand what you mean. 
This is like an All-in-one compiled to specific usage, someone buy a rpi and upsplus and will use with HA.. this is the solution.
What you are saying be possible create to specific situations on further.

Lets keep this finish one and put it running like a charm 💭 

Be free to share/propose other scripts with other goals ;)

**Comment by hellresistor** [comment]
Surprise. :)
